import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./images/picrew-img.png" />
      </Head>
      <Navbar></Navbar>
      <main className="mt-8 mb-8 flex flex-col justify-center items-center">
        <div className="relative h-64 w-64">
          <Image
            className="rounded-full"
            priority
            src="/../public/images/picrew-img.png"
            alt="Cartoon illustration of Naveen Sivasankar"
            layout="fill"
            objectFit="cover"
          />
        </div>

        <h1 className="mt-8 mb-4 text-7xl font-bold">Hello!</h1>
        <h2 className="mt-8 text-4xl font-bold w-9/12">Background</h2>
        <p className="mt-6 text-2xl w-9/12">
          I'm <strong className="text-red-500">Naveen Sivasankar</strong>, a
          soon-to-be graduate of the University of British Columbia. I have
          several years of experience developing{" "}
          <strong className="text-red-500">
            full-stack enterprise applications
          </strong>{" "}
          and even more experience with various academic projects.
        </p>
        <p className="mt-6 text-2xl w-9/12">
          My academic and professional experiences have helped me to understand
          many{" "}
          <strong className="text-red-500">
            software development processes
          </strong>{" "}
          and will allow me to work effectively with others in a professional
          setting.
        </p>
        <h2 className="mt-8 text-4xl font-bold w-9/12">Future</h2>
        <p className="mt-6 text-2xl w-9/12">
          I am still exploring my options but I am excited to work in the fields
          of <strong className="text-red-500">full-stack development</strong>,{" "}
          <strong className="text-red-500">data science</strong>, or{" "}
          <strong className="text-red-500">cloud computing</strong>. I am also
          curious about the latest technologies such as{" "}
          <strong className="text-red-500">Web3</strong> and the blockchain.
        </p>
      </main>
    </>
  );
}
